#pragma once

#include "ScrewExtend.h"

#define ELMG_TERMINAL_TRACE(...) SE_MESSAGE_TERMINAL_TRACE(__VA_ARGS__)
#define ELMG_TERMINAL_INFO(...) SE_MESSAGE_TERMINAL_INFO(__VA_ARGS__)
#define ELMG_TERMINAL_DEBUG(...) SE_MESSAGE_TERMINAL_DEBUG(__VA_ARGS__)
#define ELMG_TERMINAL_WARN(...) SE_MESSAGE_TERMINAL_WARN(__VA_ARGS__)
#define ELMG_TERMINAL_ERROR(...) SE_MESSAGE_TERMINAL_ERROR(__VA_ARGS__)
#define ELMG_TERMINAL_CRITICAL(...) SE_MESSAGE_TERMINAL_CRITICAL(__VA_ARGS__)

#define ELMG_CLIENT_TRACE(...) SE_MESSAGE_CLIENT_TRACE(__VA_ARGS__)
#define ELMG_CLIENT_INFO(...) SE_MESSAGE_CLIENT_INFO(__VA_ARGS__)
#define ELMG_CLIENT_DEBUG(...) SE_MESSAGE_CLIENT_DEBUG(__VA_ARGS__)
#define ELMG_CLIENT_WARN(...) SE_MESSAGE_CLIENT_WARN(__VA_ARGS__) 
#define ELMG_CLIENT_ERROR(...) SE_MESSAGE_CLIENT_ERROR(__VA_ARGS__)
#define ELMG_CLIENT_CRITICAL(...) SE_MESSAGE_CLIENT_CRITICAL(__VA_ARGS__)